### PR TITLE
Fixed DateTime problems in Date.js

### PR DESCRIPTION
**Pull request by yctri**
- Fixes https://github.com/bridgedotnet/Bridge/issues/3306
- Fixes https://github.com/bridgedotnet/Bridge/issues/3307
- Fixes bad DateTime when parsing UTC (Z) times.
- Fixes Date extraction not taking DateTimeKind into account.
- Mutating DateTime now sets missing Ticks member.

(First time doing a pull request here, so apologies in advance if I missed anything)

### CODE REVIEW

**Comment by geoffreymcgill** [comment]
Hi @yctri – Thanks for submitting this pull-request. 

Unfortunately, we cannot accept this pr into the 16.6.0 release, but our plan is to review immediately after the 16.6.0 release, then release a 16.6.1 with this pr.

**Comment by fabriciomurta** [comment]
You should be able to build and run the tests if you build **Bridge.Dev.sln** and run (view in browser) the **Tests/Runner** project.

**Comment by yctri** [comment]
Good to know, thanks. I won't be able to look into the failing unit tests for a while, so do feel free to take a stab at this if the fix is obvious to you guys...

Thanks

**Comment by fabriciomurta** [comment]
Hello and thanks for your feedback! We'll try on our own to see about the new issues when we get a chance.

But if you beat us to it, you're more than welcome to draw out the negative side effects of the changes. Besides, being able to run the tests on your own would greatly help you further contribute in the future.

**Comment by yctri** [comment]
Hi @fabriciomurta, I managed to resolve all of the unit test failures with the latest commit. 

Presumably during Date construction, JS converts the caller's specified time to UTC time internally before calculating its milliseconds since Unix epoch, whereas .NET's DateTime does not (since the latter relies on DateTimeKind instead). Therefore, getTicks() now checks Kind to determine whether the timezone offset was applied internally before offsetting ticks. 

Thanks for pointing out the unit tests!

**Comment by fabriciomurta** [comment]
Well, seems github is not always as smart as we expect!.. To preserve your commits as they are, I've rebased your changes to our 16.6.1 branch (we already moved `dev` into 16.7.0 with a new feature, but we really want to make a 16.6.1 with your fix, so we branched off with also other minor fixes).
Anyway, your fix has been merged and we're going to release it.
Although the pull request will read as "closed" it has been effectively merged, it is just not always github can detect a merged pull request if they didn't follow the "vanilla protocol". ;)

But see your commits here in history: https://github.com/bridgedotnet/Bridge/commits/version16.6.1

**Pull request closed without merging**
