### PR TITLE
Tiny improvements for Type

### PR DESCRIPTION
**Pull request by TriEdgeAI**
- Implemented Type.BaseType
- Implemented Type.IsAssignableFrom

### CODE REVIEW

**Comment by geoffreymcgill** [comment]
Hi @TriEdgeAI, 

In order for us to properly track these features, we need to create separate issues for each. Each issue can only have one related pull request. Only the code directly related to that issue should be in the pull request. 

I will create the two issues. When you have the chance, please separate the code in this pull request into two, or another option is to close this pull request and initiate two new pr's.

Can you provide one (or more) simple code samples for each feature. That will help with us writing some unit tests.

**Comment by geoffreymcgill** [comment]
See Issues #1419 and #1420.

**Comment by TriEdgeAI** [comment]
Sure, I'll remake the pull request later. Is it meaningful to go further and implement some more missing features for Type, considering Bridge v2 is coming (soon?) and it is going to have reflection (judging by the comment in #715)?

**Comment by geoffreymcgill** [comment]
Hi @TriEdgeAI,

You might want to hold off any new Reflection related functionality. We're working on this right now, and I can provide a status update early next week.

**Comment by TriEdgeAI** [comment]
Okay, thanks.

**Comment by geoffreymcgill** [comment]
Hi @TriEdgeAI - We plan to write a few tests for these features additions today, and will accept the pull request. The features will make it into the Bridge 1.14 release. 

At this point, no need to split into separate pr's. 

These two are commits are very related and make up one unit of work, so the splitting into separate pull requests would not be required anyways. 

Creating individual Issues for each Feature Request is something we require which helps easily track what's new in the release.

Thanks for your help.

**Comment by TriEdgeAI** [comment]
I got time now. Should I split it into two separate PRs?

**Comment by LeonidVeriga** [comment]
@TriEdgeAI, no, it is not required for this pull request as the two issues are related to it.

**Comment by LeonidVeriga** [comment]
@TriEdgeAI, we reviewed and merged this PR into master branch for 1.14 release. Thank you for contribution again!

We commited a couple of changes including tests. You can review - they are all linked to this PR. The main thing is changing `Function.prototype.isAssignableFrom` o `Bridge.isAssignableFrom` to avoid changing Function's prototype.

**Pull request merged**
