### PR TITLE
Fixed #2034: Window.OnError wrong arguments.

### LINKED ISSUE #2034: Window.OnError wrong arguments
`Window.OnError` is `Action<Event>`, but it should be `Action<string, string, int, int, Error>` according to:
https://developer.mozilla.org/en/docs/Web/API/GlobalEventHandlers/onerror

### PR DESCRIPTION
**Pull request by TriEdgeAI**
Fixed #2034: Window.OnError wrong arguments.

### CODE REVIEW

**Comment by LeonidVeriga** [comment]
Hi @TriEdgeAI, thanks for the Pull Request.

Looks like it can be even improved:
- `WindowInstance.OnError Action<Event>` should be also changed;
- There is an existing `ErrorEventHandler` that can be used instead of `Action<string, string, int, int, Error>`
  And there is a bug with `ErrorEventHandler` itself (uses last parameter as `Exception` instead of `Error`) that your PR has discovered (:+1:).

**Comment by TriEdgeAI** [comment]
Oh, yes. I was going to suggest using a delegate instead of Action<> in this case, because we will have names for the arguments. Definitely a better idea.

**Comment by TriEdgeAI** [comment]
How about now?

**Comment by TriEdgeAI** [comment]
I was experimenting just now and found something interesting. While the correct argument really is Error, sometimes a System.Exception will be passed there, which does not inherit from Error.
In fact as I tested more, I believe the type of the last argument should be object, because JavaScript will pass absolutely anything that you throw. You can even do:

```js
throw 5;
```

...and the last argument of your onerror handler will be set to 5.

**Comment by LeonidVeriga** [comment]
Yes, a nice catch!

So that an error handler would look like:
```
void ErrorHandler(string message, string url, int lineNumber, int columnNumber, object error)
{
    Console.WriteLine("message: " + message);
    Console.WriteLine("url: " + url);
    Console.WriteLine("lineNumber: " + lineNumber);
    Console.WriteLine("columnNumber: " + columnNumber);
    Console.WriteLine("error: " + error);

    Error er = error as Error;
    if (er != null)
    {
        Console.WriteLine("As Error: " + er.Message);
    }

    Exception ex = error as Exception;
    if (ex != null)
    {
        Console.WriteLine("As Exception: " + ex.Message);
    }

    object o = error;
    if (o != null)
    {
        Console.WriteLine("As Object: " + o.ToString());
    }
}
```

**Comment by TriEdgeAI** [comment]
Exactly. ;)

**Comment by LeonidVeriga** [comment]
### Summary of changes

Changed `Action<Event> OnError` to `ErrorEventHandler OnError` for the following classes:
- `HTMLBodyElement `
- `Global`
- `Window`
- `WindowInstance`

Changed `ErrorEventHandler` delegate to have `error` parameter of `object` type:
```cs
public delegate bool ErrorEventHandler(string message, string url, int lineNumber, int columnNumber, object error);
```

**Pull request merged**
