### PR TITLE
Added BitConverter.

### PR DESCRIPTION
**Pull request by michaelcheers**
Added all **BitConverter** methods.

**Note:** NaN has a different preferred bit pattern in javascript (111111111111000000000000000000000000000000000000000000000000000) and c# (1111111111111000000000000000000000000000000000000000000000000000) so **GetBytes** and **DoubleToInt64Bits** have different results when invoked with `double.NaN`. C# has one more 1.

**Note:** I wasn't sure what to put for **BitConverter.IsLittleEndian** so I didn't implement it.

### CODE REVIEW

**Comment by michaelcheers** [comment]
Should I create an issue for this?

**Comment by michaelcheers** [comment]
Is this planning to be merged?

**Comment by LeonidVeriga** [comment]
Hi @michaelcheers,
Yes, most likely in **v16.0**.

**Comment by geoffreymcgill** [comment]
Our goal is to review this pull request and write tests this week. With some luck, this functionality will be included in the **master** branch before the end of the week.

**Comment by LeonidVeriga** [comment]
Hi @michaelcheers,

We reviewed this Pull Request and based on your ideas created a new one that will be incorporated into the next release (#2453).

**Pull request closed without merging**
