### PR TITLE
Value field for TextAreaElement

### LINKED ISSUE #816: TextAreaElement misses Value field
See https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement

### PR DESCRIPTION
**Pull request by AndreyChechel**
This pull request adds missed Value field for TextAreaElement (fixes #816).

### CODE REVIEW

**Comment by LeonidVeriga** [comment]
Hi @AndreyChechel.

Thank you for the Pull Request. Can you please sign our [CLA form](https://docs.google.com/a/object.net/forms/d/12IAxRmWCk2vD-M3mj4d0ihztqKoiREpRRSVq4pEk0-k/viewform?c=0&w=1) before we can accept the PR.

There are related documents:
[Contributing document](https://github.com/bridgedotnet/Bridge/blob/master/CONTRIBUTING.md)
[CLA document](https://github.com/bridgedotnet/Bridge/blob/master/CLA.md)

**Comment by DaniilVeriga** [comment]
Thank you for signing CLA.
Before merging the pull request we'll need to add a test of the new property.

**Comment by LeonidVeriga** [comment]
@AndreyChechel,
Yes, a test checking the field is greatly appreciated.

**Comment by AndreyChechel** [comment]
Hi @LeonidVeriga, @DaniilVeriga - thanks for the response! I will provide a test for this issue soon

**Comment by AndreyChechel** [comment]
Hi, I've created a test for the introduced property. Unfortunately, I can't verify whether it works correctly with the new approach to unit testing, as `master` branch at the moment can't be compiled. Once you guys stabilize the branch please let me know if we can close this issue.

**Comment by LeonidVeriga** [comment]
@AndreyChechel, sorry for the inconvinience. Thank you for adding a test in a new format. You did it almost 100% right - I just have to amend it a little.

We accepted your PR. Thanks a lot for contributing.

**Pull request merged**
