### PR TITLE
Issue3805 Cache references for next compilation

### PR DESCRIPTION
**Pull request by colderlord**
Guys.
You load same references 2 times:
1st with roslyn
2nd with nrefactory

Please choose one of this libries in future. Make some tests or something please.

### CODE REVIEW

**Comment by colderlord** [comment]
Now, when you build many projects in 1 time compilation superfast

**Comment by fabriciomurta** [comment]
Awesome, thank you for signing the CLA!

We will be pointing the base/target branch to our side's `dev`, that's where we pull everything together before making the release. It will probably show conflicts soon, as we merge other pull requests together, but your changes looks straightforward enough not to impose any "heavy" conflicts. We'll let you know if we get in trouble trying to merge it.

We usually ask for unit tests for issues fixed, but in this case I'm not sure we can come up with any. The very fact the unit test projects compiles should prove that the fix is not breaking anything.

**Comment by geoffreymcgill** [comment]
Hi @colderlord, 

We ran a variety of performance tests with and without this PR, and we're not seeing any performance improvements. 

bridge-performance-3806

Are you seeing better performance improvements in your project(s)?

**Comment by colderlord** [comment]
Hello!
I used as example your [test project](https://github.com/bridgedotnet/Bridge/blob/v17.4.0/Compiler/TranslatorTests/IntegrationTests/IntegrationTest.cs#L238-L255) and maked my own `TranslatorRunner` and `Translator`.

As you can see i dont change any logic, thats why build time is the same. My optimization work when you build many projects, because i wrote cache for references in this PR. 

Here is my example:
```
class Program
{
	private static string projectDir = @"C:\Users\d.popov\Documents\Visual Studio 2015\Projects\ClassLibrary1\ClassLibrary1\";
	private static string sourcePath = $"{projectDir}MyClass.cs";
	private const string LogFileNameWithoutExtention = "testProjectsBuild";

	static void Main(string[] args)
	{
		
		var logger = new Logger(null, true, new ConsoleLoggerWriter());
		logger.LoggerLevel = LoggerLevel.None;

		var translator = new TranslatorRunner
		{
			Logger = logger,
			Assembly = File.ReadAllBytes(@"C:\Users\d.popov\Documents\Visual Studio 2015\Projects\ClassLibrary1\ClassLibrary1\bin\Debug\ClassLibrary1.dll"),
			Sources = sourcePath,
		};

		var bridgeDll = AssemblyDefinition.ReadAssembly(@"C:\Users\d.popov\Documents\Visual Studio 2015\Projects\ClassLibrary1\ClassLibrary1\bin\Debug\Bridge.dll");
		translator.AddNestedTypes(bridgeDll.MainModule.Types);

		Stopwatch stopWatch = new Stopwatch();
		stopWatch.Start();
		translator.Translate(false); // 3 sec
		stopWatch.Stop();
		Console.WriteLine(string.Format("BuildAll Time {0}", stopWatch.Elapsed));

		Stopwatch stopWatch1 = new Stopwatch();
		stopWatch1.Start();
		translator.Translate(false); // 0,09 sec
		stopWatch1.Stop();
		Console.WriteLine(string.Format("BuildAll2 Time {0}", stopWatch1.Elapsed));

		Console.ReadKey();
	}
}
```

As you can see i use builded assembly to translate csharp to js. First `translate` will always slow (about 3 secs), next will be faster (0,09-0,1 secs) because of caching.
I measured on what takes the whole 3 seconds at compilation. And finded 2 places that i optimezed now. You took all references and compiled library, load them from disk and disassemble them every time. Because of caching this operation should be faster

**Comment by fabriciomurta** [comment]
#3805 (just referencing the issue from the pull request)

**Pull request merged**
