### PR TITLE
Added Char.IsDigit

### PR DESCRIPTION
**Pull request by Dim0N22**
Hello. I'm new to Bridge but I think it is a very interesting framework.

I've tried to implement Char.IsDigit function, but I really don't see how do you get minimized bridge.js file. 

Could you help, please? I'll continue to implement Char functions. 

Thank you.

### CODE REVIEW

**Comment by Dim0N22** [comment]
Sorry, I've found Knowledge Base on bridge.net. Still it would be nice to have a link from GitHub.

**Comment by geoffreymcgill** [comment]
Thanks for `Char.IsDigit`. We'll review right away. To build `bridge.js` and `bridge.min.js`, double-click the following file (in your local File Explorer). 

https://github.com/bridgedotnet/Bridge/blob/master/Bridge/Resources/build.bat

**Comment by Dim0N22** [comment]
Found it just minutes before you created the comment.

Thank you for help!

**Comment by geoffreymcgill** [comment]
@vladsch we should just add this `build.bat` call to the Pre-build step. I've been tripped up a couple times by forgetting to run this file. It's so quick to run that adding to Pre-build should not be noticeable.

**Comment by Dim0N22** [comment]
I think it's better to create separate Char object in js. What do you think?

**Comment by Mimisss** [comment]
@Dim0N22 It will be needed sooner or later especially to implement the rest of the Char class methods like IsControl, IsLetter, IsNumber, etc.

**Comment by geoffreymcgill** [comment]
Yes, a separate **Char.js** file is required, and we can get working on a `Bridge.Char.*` API.

**Comment by geoffreymcgill** [comment]
@Mimisss There is some overlap in the work being done in this thread with Issue #132. Can you coordinate?

**Comment by Dim0N22** [comment]
@Mimisss just tell what part should I focus on.

**Comment by Mimisss** [comment]
@geoffreymcgill No, fortunately there is not. 

@Dim0N22 Feel free to work on the Char methods mentioned in #132.

**Comment by Mimisss** [comment]
@Dim0N22 

Tip 1: `char` is treated as its numeric value. There is `String.fromCharCode` to get the corresponding character.

Tip 2: The `[Template("({ch} >= 48 && {ch} <= 57)")]` "implementation" of the `Char.IsDigit` method is a nice "shortcut" way to implement methods. 

Tips 1 & 2 example: This: 
`Console.WriteLine(char.IsDigit('5'));`

is translated to:

`console.log((53 >= 48 && 53 <= 57));`

**Comment by Dim0N22** [comment]
@Mimisss
Tip 1: Thank you, I will investigate it.

Tip 2: I think it is more consistent to have all the ```Char``` logic in ```Char``` object. Having logic in the ```Template``` is a bit frustrating and not what an user can expect. Anyway you decide.

**Comment by Mimisss** [comment]
@Dim0N22 Tip 2: Absolutely. I mentioned `Template` because it can be handy in some situations; with overloaded methods, for example, where all you want is to call the same function defined in `Char.js` with adjusted parameters.

**Comment by geoffreymcgill** [comment]
Hi @Dim0N22, 

Just to let you know we haven't forgotten about this pull request. I will be reviewing the current status of the Char class tomorrow (Thursday). 

Hope all is well with you. Feel free to contact me (geoff@object) directly any time if you have questions or comments. 

Thanks again for contributing this pr.

**Comment by Dim0N22** [comment]
@geoffreymcgill Hi.

Thank you for your time! 
I am afraid I have no idea how to implement Char in JS with handling all the unicode characters. Probably you have an idea?

**Comment by Mimisss** [comment]
This is the best resource I've found so far: 
http://xregexp.com/plugins/

Such a solution is needed to categorize characters beyond ASCII.

**Comment by Mimisss** [comment]
Char methods have been added to the master repo.

**Pull request closed without merging**
