### PR TITLE
[2406] Support Task.Wait Method

### LINKED ISSUE #2406: Support Task.Wait Method
https://msdn.microsoft.com/en-us/library/system.threading.tasks.task.wait(v=vs.110).aspx

### Steps To Reproduce

http://deck.net/85271e9aa4b48060ce45751998acb622

```c#
using System;
using System.Threading.Tasks;

public class Example
{
    public static void Main()
    {
        Task t = Task.Run(() => 
        {
            Random rnd = new Random();
            long sum = 0;
            int n = 5000000;
            
            for (int ctr = 1; ctr <= n; ctr++) 
            {
                int number = rnd.Next(0, 101);
                sum += number;
            }

            Console.WriteLine("Total:   {0:N0}", sum);
            Console.WriteLine("Mean:    {0:N2}", sum/n);
            Console.WriteLine("N:       {0:N0}", n);   
        });

        TimeSpan ts = TimeSpan.FromMilliseconds(150);
        
        if (! t.Wait(ts))
        {
           Console.WriteLine("The timeout interval elapsed.");
        }
    }
}

// The example displays output similar to the following:
//       Total:   50,015,714
//       Mean:    50.02
//       N:       1,000,000
// Or it displays the following output:
//      The timeout interval elapsed.
```

## See Also

* http://forums.bridge.net/forum/general/feature-requests/3533-task-delay-with-cancellationtoken-support
* #2405
* https://gitter.im/bridgedotnet/Bridge?at=5c87d7fb1fae6423ca732aea

### PR DESCRIPTION
**Pull request by vladsch**
Fixes #2406 

Changes proposed in this pull request:

- It is a partial implementation of Task.Wait. The overloads with timeout are not supported still.

### CODE REVIEW

**Comment by vladsch** [comment]
Timers and cancellation support has been added

**Comment by fabriciomurta** [comment]
Looked good, just forgot to place the new review before I pushed the merge.

**Comment by miladsadeghi72** [comment]
https://github.com/bridgedotnet/Bridge/issues/3940

**Comment by miladsadeghi72** [comment]
please check this

**Pull request merged**
