### PR TITLE
Building on Linux

### PR DESCRIPTION
**Pull request by wind39**
I tried to build Bridge on both inside MonoDevelop and using xbuild on console. Both can't build with the following error:

```
Building: Bridge (Debug)

Build started 11/06/2015 22:09:11.
__________________________________________________
Project "/work/projects/Repositories/Bridge/Bridge/Bridge.csproj" (Build target(s)):
	
	Target PrepareForBuild:
		Configuration: Debug Platform: AnyCPU
	
	Target PreBuildEvent:
		Executing: "/work/projects/Repositories/Bridge/Bridge//Resources/build.bat"
		/work/projects/Repositories/Bridge/Bridge//Resources/build.bat: 1: /work/projects/Repositories/Bridge/Bridge//Resources/build.bat: %~dp0\JSBuilder\JSBuildConsole.exe: not found
		/work/projects/Repositories/Bridge/Bridge//Resources/build.bat: 3: /work/projects/Repositories/Bridge/Bridge//Resources/build.bat: move: not found
		/work/projects/Repositories/Bridge/Bridge//Resources/build.bat: 4: /work/projects/Repositories/Bridge/Bridge//Resources/build.bat: move: not found
/usr/lib/mono/4.5/Microsoft.Common.targets: error : Command '"/work/projects/Repositories/Bridge/Bridge//Resources/build.bat"' exited with code: 127.
	Task "Exec" execution -- FAILED
	Done building target "PreBuildEvent" in project "/work/projects/Repositories/Bridge/Bridge/Bridge.csproj".-- FAILED
	
Done building project "/work/projects/Repositories/Bridge/Bridge/Bridge.csproj".-- FAILED

Build FAILED.
Errors:

/work/projects/Repositories/Bridge/Bridge/Bridge.csproj (Build) ->
/usr/lib/mono/4.5/Microsoft.Common.targets (PreBuildEvent target) ->


---------------------- Done ----------------------

Build: 1 error, 0 warnings
```

With the proposed solution files, I'm able to build Bridge on Linux.

### CODE REVIEW

**Comment by fabriciomurta** [comment]
Oh awesome! Thank you very much for your contribution! We're further discussing this on #106.

I'll discuss with our colleagues here about the implications of adding more .csproj files to the root of the repo (we might restrain from doing it for simplicity matters, for example).

By the way, before we accept your pull request, we need you to accept and sign our CLA. Sorry for the bureaucratic matter, but that's to ensure nobody ends up hurt in the end of the code merge. :)
Here what you need to know:
[Contributing document](https://github.com/bridgedotnet/Bridge/blob/master/CONTRIBUTING.md)
[CLA document](https://github.com/bridgedotnet/Bridge/blob/master/CLA.md)
[CLA signing form](https://docs.google.com/a/object.net/forms/d/12IAxRmWCk2vD-M3mj4d0ihztqKoiREpRRSVq4pEk0-k/viewform?c=0&w=1)

Sorry for that, we're very excited by your contributions and willing to support you the best way, hope you understand. :+1:

**Comment by wind39** [comment]
Of course I understand, you don't need to be sorry. You are doing your best to protect and guarantee maximum quality on Bridge.NET, and that's awesome! :)

I already read both documents and filled CLA signing form.

**Comment by fabriciomurta** [comment]
Hello, I had a better look at your solution but it seems it is not the best approach. Instead, can you try the following:
Open in a text editor whatever .sln file you're opening with MonoDevelop. I used here the `Bridge.Frameworks.Builder.sln`.

Find on the bottom of the file a line that reads:
```
<PreBuildEvent>"$(ProjectDir)\Resources\build.bat"</PreBuildEvent>
```

Then change it to:
```
<PreBuildEvent Condition="$(OS) != Unix">"$(ProjectDir)\Resources\build.bat"</PreBuildEvent>
```

I was able to build the full solution with this. Could you check if this fixes build at your side as well? 

Although this can fix the building, this brings other problems. The `build.bat` script merges the different Bridge.NET main JavaScript files into the main `bridge.js` for minifying and embedding. Not running this step during build time may mean that a change directly to one or more JavaScript-side files will not reflect to actual Bridge base JavaScript.

Then, I can say that instead of just having the change above, we would need something like this in the end:
```
<PreBuildEvent Condition="$(OS) != Unix">"$(ProjectDir)\Resources\build.bat"</PreBuildEvent>
<PreBuildEvent Condition="$(OS) == Unix">"$(ProjectDir)\Resources\build.sh"</PreBuildEvent>
```

With a `build.sh` corresponding to the `build.bat` for the unix platform.

Once this is accomplished, we can say that Bridge.NET building process is fully supported on Unix environment.

Please let me know if the proposed change above works for you as well. It will be much better to maintain than having different solution files.

**Comment by wind39** [comment]
@fabriciomurta I didn't know about this `Condition="$(OS) == Unix"` option. Thank you for pointing that out.
I reforked and created a new PR [#270](https://github.com/bridgedotnet/Bridge/pull/270).

**Comment by fabriciomurta** [comment]
=]

**Comment by hardhub** [comment]
Why do you need CLA? If it is under  Apache License?

> Submission of Contributions: Unless You explicitly state otherwise, any Contribution intentionally submitted for inclusion in the Work by You to the Licensor shall be under the terms and conditions of this License, without any additional terms or conditions. Notwithstanding the above, nothing herein shall supersede or modify the terms of any separate license agreement you may have executed with Licensor regarding such Contributions.

In my (rather limited) experience a CLAs often grant the project owners permission to use the contributed code not only under the license in effect when the contribution was made, but under others as well. So if for some reason you decide to switch the whole project from Apache 2 to MIT or GPL 2 or whatever, doing so can be fine if your contributers signed a CLA which covered such scenarios, but with Apache 2 behavior you'd still have to ask each such contributor for their agreement.

So my question.. to which license do you plan to switch project in the future?

**Comment by fabriciomurta** [comment]
Hello! Been [apache license 2](https://github.com/bridgedotnet/Bridge/blob/master/LICENSE.md) for some time now (@358a84fdbcb6e8e18a1d0f05bdd230ed062e8906), I'm not sure where your question is coming from, but maybe you want to discuss this on [Bridge.NET community forums](http://forums.bridge.net/)?

**Comment by hardhub** [comment]
Hello!

You said in this post this:
> By the way, before we accept your pull request, we need you to accept and sign our CLA. Sorry for the bureaucratic matter, but that's to ensure nobody ends up hurt in the end of the code merge. :)

So I am asking it here :)

CLA was a bit strange... Now when you have changed license from MIT to Apache all is clear...
But it also could be possible that you will make it licensed under EULA? And any future versions will not be free anymore...
May I ask why was it necessary to change from MIT to Apache? Many JS targeted libraries like Bootstrap are released under MIT.

P.S. yes, I think finally I will come to yours forums... I will have a lot of questions... But at least this license topic we can leave here I think...

**Comment by fabriciomurta** [comment]
We have a forums section dedicated for licensing questions. Although no threads there yet, yours could be the first one! :) Of course, you can open the discussion there and mention this pull request (by a link, perhaps), so you can get a better answer. Bridge has changed a LOT since this pull request. And I mean that. :)

I only seen your inquiry here cause I was the one handling this pull request. I believe moving the discussion there will allow other people to follow the discussion. And also people with the same question would be finding it there. Additionally the rest of the Bridge team that are not following this pull request will also be watching it then.

**Pull request closed without merging**
