### PR TITLE
Fixed #1344 Fields cannot be named __proto__

### LINKED ISSUE #1344: Fields cannot be named __proto__
### Expected
```
True
```
### Actual
```javascript
false
```
### Steps To Reproduce
[Live Bridge](http://live.bridge.net/#344ddb787193fdf18fa2ac95f1d97afb)
```csharp
/// <summary>
/// Creates a simple class
/// </summary>
public class App
{
    public string __proto__;
    
    public App ()
    {
        __proto__ = "hello world";
        Console.WriteLine(__proto__ == "hello world");
    }
    
    // Use the [Ready] attribute to automatically
    // run this method when the page is ready.
    [Ready]
    public static void Main()
    {
        App app = new App();
    }
}
```

### PR DESCRIPTION
**Pull request by michaelcheers**

### CODE REVIEW

**Comment by LeonidVeriga** [comment]
@michaelcheers, It seems not to fix the problem. I run the test case you provided ([Live](http://live.bridge.net/#344ddb787193fdf18fa2ac95f1d97afb)) and it failed.
Can you please double check the fix.

**Comment by michaelcheers** [comment]
I think that's because of: [this pull request](https://github.com/bridgedotnet/Bridge/pull/1279/files#diff-24ea6f9a33f1688149827b23cd3b614fL74).

**Comment by LeonidVeriga** [comment]
Yes, right, @michaelcheers. That is the reason we recommend use the latest source code as a base branch for pull requests - that merged PR is 26 days old.

**Comment by LeonidVeriga** [comment]
Thanks, @michaelcheers, merged.

**Pull request merged**
