### PR TITLE
Made Bridge.NET compatible with Visual Studio 2019

### LINKED ISSUE #4112: Bridge.sln does not build with Visual Studio 2019 16.4.3
Bridge.NET does not seem to fully build on the latest version of Visual Studio. It seems to be able to build _bridge.exe_, but executing it raises the same error in runtime.

There seems to be a dependency to `System.String.GetPathsOfAllDirectoriesAbove` that cannot be resolved.

I could be doing somehing wrong. If I am, the documentation should probably be updated, as I did exactly what's written here:
https://github.com/bridgedotnet/Bridge/wiki/Build-From-Source

### Steps To Reproduce

1. Clone the master branch of the Bridge.NET repo.
2. Open Bridge.sln in Visual Studio 2019 version 16.4.3.
3. Try to build it without changing anything.

```
1>------ Build started: Project: Bridge.Translator, Configuration: Debug Any CPU ------
1>  All packages listed in packages.config are already installed.
1>  Bridge.Translator -> D:\Git\Bridge\Compiler\Translator\bin\Debug\Bridge.Translator.dll
2>------ Build started: Project: Bridge.PostBuild, Configuration: Debug Any CPU ------
2>  Executing Bridge.Builder.Console...
2>EXEC : Bridge.NET Compiler error : Microsoft.Build.Exceptions.InvalidProjectFileException: The expression ""Attributes\ConventionAttribute.cs".GetPathsOfAllDirectoriesAbove()" cannot be evaluated. Finner ikke metoden System.String.GetPathsOfAllDirectoriesAbove.  C:\Program Files (x86)\Microsoft Visual Studio\2019\MSBuild\Current\Bin\Roslyn\Microsoft.Managed.Core.targets
2>     ved Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args) i /_/src/Shared/ProjectErrorUtilities.cs:linje 412
2>     ved Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1,T2](IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1) i /_/src/Shared/ProjectErrorUtilities.cs:linje 98
2>     ved Microsoft.Build.Evaluation.Expander`2.Function`1.Execute(Object objectInstance, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation) i /_/src/Build/Evaluation/Expander.cs:linje 3312
2>     ved Microsoft.Build.Evaluation.Expander`2.ItemExpander.IntrinsicItemFunctions`1.<ExecuteStringFunction>d__13.MoveNext() i /_/src/Build/Evaluation/Expander.cs:linje 2446
2>     ved Microsoft.Build.Evaluation.Expander`2.ItemExpander.<Transform>d__0`1.MoveNext() i /_/src/Build/Evaluation/Expander.cs:linje 1628
2>     ved Microsoft.Build.Evaluation.Expander`2.ItemExpander.<Transform>d__0`1.MoveNext() i /_/src/Build/Evaluation/Expander.cs:linje 1619
2>     ved Microsoft.Build.Evaluation.Expander`2.ItemExpander.ExpandExpressionCapture[S](Expander`2 expander, ItemExpressionCapture expressionCapture, IItemProvider`1 evaluatedItems, IElementLocation elementLocation, ExpanderOptions options, Boolean includeNullEntries, Boolean& isTransformExpression, List`1& itemsFromCapture) i /_/src/Build/Evaluation/Expander.cs:linje 1879
2>     ved Microsoft.Build.Evaluation.Expander`2.ItemExpander.ExpandExpressionCaptureIntoItems[S,T](ItemExpressionCapture expressionCapture, Expander`2 expander, IItemProvider`1 items, IItemFactory`2 itemFactory, ExpanderOptions options, Boolean includeNullEntries, Boolean& isTransformExpression, IElementLocation elementLocation) i /_/src/Build/Evaluation/Expander.cs:linje 1765
2>     ved Microsoft.Build.Evaluation.LazyItemEvaluator`4.IncludeOperation.SelectItems(Builder listBuilder, ImmutableHashSet`1 globsToIgnore) i /_/src/Build/Evaluation/LazyItemEvaluator.IncludeOperation.cs:linje 70
2>     ved Microsoft.Build.Evaluation.LazyItemEvaluator`4.LazyItemOperation.Apply(Builder listBuilder, ImmutableHashSet`1 globsToIgnore) i /_/src/Build/Evaluation/LazyItemEvaluator.LazyItemOperation.cs:linje 56
2>     ved Microsoft.Build.Evaluation.LazyItemEvaluator`4.MemoizedOperation.Apply(Builder listBuilder, ImmutableHashSet`1 globsToIgnore) i /_/src/Build/Evaluation/LazyItemEvaluator.cs:linje 190
2>     ved Microsoft.Build.Evaluation.LazyItemEvaluator`4.LazyItemList.ComputeItems(LazyItemList lazyItemList, ImmutableHashSet`1 globsToIgnore) i /_/src/Build/Evaluation/LazyItemEvaluator.cs:linje 312
2>     ved Microsoft.Build.Evaluation.LazyItemEvaluator`4.LazyItemList.GetItemData(ImmutableHashSet`1 globsToIgnore) i /_/src/Build/Evaluation/LazyItemEvaluator.cs:linje 304
2>     ved System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
2>     ved System.Linq.Buffer`1..ctor(IEnumerable`1 source)
2>     ved System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
2>     ved Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext) i /_/src/Build/Evaluation/Evaluator.cs:linje 713
2>     ved Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) i /_/src/Build/Definition/Project.cs:linje 2728
2>     ved Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) i /_/src/Build/Definition/Project.cs:linje 2688
2>     ved Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) i /_/src/Build/Definition/Project.cs:linje 2799
2>     ved Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext) i /_/src/Build/Definition/Project.cs:linje 516
2>     ved Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ProjectCollection projectCollection) i /_/src/Build/Definition/Project.cs:linje 434
2>     ved Bridge.Translator.Translator.OpenProject(String location, IDictionary`2 globalProperties) i D:\Git\Bridge\Compiler\Translator\Translator\Translator.ProjectReader.cs:linje 37
2>     ved Bridge.Translator.Translator.EnsureProjectProperties() i D:\Git\Bridge\Compiler\Translator\Translator\Translator.ProjectReader.cs:linje 51
2>     ved Bridge.Translator.TranslatorProcessor.SetTranslatorProperties() i D:\Git\Bridge\Compiler\Translator\Translator\TranslatorProcessor.cs:linje 352
2>     ved Bridge.Translator.TranslatorProcessor.PreProcess() i D:\Git\Bridge\Compiler\Translator\Translator\TranslatorProcessor.cs:linje 34
2>     ved Bridge.Builder.Program.Main(String[] args) i D:\Git\Bridge\Compiler\Builder\Program.cs:linje 41
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1328,5): error MSB3073: The command "
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1328,5): error MSB3073: REM Run Bridge Compiler for the project
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1328,5): error MSB3073: "D:\Git\Bridge\Compiler\Builder\bin\Debug\bridge.exe" -p "D:\Git\Bridge\Bridge\Bridge.csproj" -b "D:\Git\Bridge\Bridge\bin\Debug\Bridge.dll" -cfg "Debug" --platform "AnyCPU"
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(1328,5): error MSB3073: " exited with code 1.
3>------ Build started: Project: Bridge.Translator.Tests, Configuration: Debug Any CPU ------
3>  All packages listed in packages.config are already installed.
3>  Bridge.Translator.Tests -> D:\Git\Bridge\Compiler\TranslatorTests\bin\Debug\Bridge.Translator.Tests.dll
========== Build: 2 succeeded, 1 failed, 5 up-to-date, 0 skipped ==========
```

### PR DESCRIPTION
**Pull request by ChrML**
Closes #4112.

Made Bridge.NET compatible with Visual Studio 2019 and the newest MSBuild tools.

This may break compatibility with older Visual Studio 2017 versions.. but hey, it's a step forward, 2019 is newer and better than 2017 :).

Changes that had to be done:
- Suppress a new warning introduced in later versions of Visual Studio for `ValueTuple.cs`:
  `Field foo' is never assigned to, and will always have its defaule value null' (CS0649) (Assembly-CSharp)`

- Upgrade *Microsoft.Build* and *Microsoft.Build.Framework* from version `16.0.461` to the latest version `16.5.0`. Newer versions of Visual Studio no longer supports older versions of *Microsoft.Build*, as they cause this error: #4112

### CODE REVIEW

**Comment by ChrML** [comment]
There seems to be an issue with the tests caused by year `2020` generated vs `2019` expected in the js file comparison. Can anyone give me a hint what should be changed?

**Comment by fabriciomurta** [comment]
If you mean project/integration tests (NUnit, and not those QUnit client-side tests), it is just a matter of updating the reference files in most situations. This may sound a little too naïve a test, but they helped more than a couple times to avoid breaking changes, document and avoid (when undesirable) side effects of changes. These just require manual checks of the changes in files' output against their expected ones and most times the reference files are just replaced by the new ones.

By your commit 653d7fc, it looks like a NUnit test issue, as QUnit tests shouldn't be affected by changes in javascript files' contents.

To identify the affected file just read thru the error message, at some point it shows reference and actual value and what changed in them -- this is probably about where you found the year change was the culprit.

Hope this helps!

About the changes in the pull request, it does not look like something we can avoid, as even if we deploy the specific MSBuild NuGet package, Visual Studio ends up linking to its active one, no matter what. Maybe an alternative to this (for backwards compatibility) would be to switch build from the MSBuild Task in project file to commandline call (so it doesn't reuse loaded references).

Now, about the suppressed warning, I believe we'd better off with `#pragma` -if- that specific scenario is strictly required; something like this: [bridgedotnet/Bridge/Tests/Batch3/BridgeIssues/1900/N1955.cs#L21-L23](https://github.com/bridgedotnet/Bridge/blob/693a8e68269f806b1dea4695317d713e74337dc9/Tests/Batch3/BridgeIssues/1900/N1955.cs#L21-L23))

Last, but not least, thanks for the contribution!

**Comment by ChrML** [comment]
@fabriciomurta Thanks, I'll look at this!

I don't think backward compatibility is something to go for if it increases complexity, like it would do if we manually execute the command line. Out of the box is usually better, and sooner or later one has to upgrade (can't stay on an old version forever).

I'll update the PR.

**Comment by ChrML** [comment]
@fabriciomurta Fixed the test that failed and moved the suppression to the actual code that generated the warning. I don't think there's much else that can be done for fixing the warning other than suppressing it.

**Comment by fabriciomurta** [comment]
Hello @ChrML ! I'm thinking on skipping most of your pull request (use the pragma and maybe the tests year refresh).

As it is useless to select a NuGet package for `Microsoft.Build.*` (because Visual Studio loads it in memory at build-time and obliges to use its own version), it may be better to just "give in" and let Bridge use Visual Studio's -- that is, turn the NuGet reference into an extension reference for the msbuild dependencies.

With a fresh VS update I could reproduce the issue you reported and was able to get Bridge to build + run if I just switched those references. And this is likely to allow building Bridge from VS2017, and avoiding the hassle to upgrade the NuGet package every time VS introduces some kind of breaking change with msbuild like this time.

Any thoughts about that?

**Comment by fabriciomurta** [comment]
I have created and tested pull request #4118 with the "relaxation" of the `Microsoft.Build` package dependency. This should work across versions and avoid the need to keep upgrading the NuGet packages as Visual Studio evolves. We can't choose the Microsoft.Build version at build time anyway, and the NuGet package is only effectively used when called from command line, resulting in, among other things, the issue that required this pull request.

Will leave it a few days in case you have a strong opinion to share about the alternative approach, then merge (in that case, that pull request will be using your commit that added the `#pragma` lines).

**Comment by ChrML** [comment]
@fabriciomurta I agree with the change, it's better as it doesn't break compatibility with older VS. Go on! :)

**Comment by fabriciomurta** [comment]
Okay, merged. I will be closing this one, but know your efforts weren't in vain, they just helped understand the problem so one (hopefully) slightly better solution could be found.

Thank you very much for your contribution!

**Pull request closed without merging**
