### PR TITLE
[#974] TouchEvent, Touch and TouchList

### PR DESCRIPTION
**Pull request by TinkerWorX**
#974

I made this PR to get a feel of the process. This is my first PR for a large project, so I am sorry if I missed something obvious.

I have added `TouchEvent`, `Touch` and `TouchList` per the definitions on [MDN](https://developer.mozilla.org/), and an enumerator for the `TouchList`. I have tested and verified the code in my own environment using my own smartphone. I'm not sure how to setup unit tests for user input like this. I would like some feedback on the following points. 
* Does the file locations make sense?
* I did not split up the `TouchList` and `TouchListEnumerator`, is this a problem?
* Should I be making interfaces enumerable like this and make helper classes like the enumerator?
* I updated the touch event fields in `Element`, is this a problem? I could imagine it might break some projects.
* Would this be considered good for a PR, if I decide to make more interfaces like this?

### CODE REVIEW

**Comment by TinkerWorX** [comment]
I just realized I accidentally added a reference to `System`. It seems this happens automatically when I create a new class in Visual Studio.

**Comment by geoffreymcgill** [comment]
Hi @TinkerWorX : Thanks for the pull request.

Before accepting your pull request, we would need the CLA [form](http://goo.gl/forms/CvDFLA3EPO) accepted. You can find more information in [CONTRIBUTING.md](https://github.com/bridgedotnet/Bridge/blob/master/CONTRIBUTING.md). 

The full CLA is available [here](http://bridge.net/cla/).

When you get a chance, please review the CLA and complete the [CLA Acceptance Form](http://goo.gl/forms/CvDFLA3EPO). If you have any questions, please just let me know.

**Comment by TinkerWorX** [comment]
The CLA has been signed. I noticed that I should only be committing single files. Should I correct this?

**Comment by geoffreymcgill** [comment]
> The CLA has been signed.

Thanks. We'll start the review.

> I noticed that I should only be committing single files. Should I correct this?

One class per file is preferred.

**Comment by LeonidVeriga** [comment]
Hi @TinkerWorX !

Thanks for the contribution! We create an issue #974 to track the change.
Some commits were made correct the code, you can check the commits under #974.

Demo is available at http://testing.bridge.net/TouchTest/demo.html

**Pull request merged**
