### PR TITLE
Add support for new csproj format

### PR DESCRIPTION
**Pull request by Danielku15**
Fixes #3340.

Changes proposed in this pull request:

- Updates unit tests to year 2018
- Replace simple msbuild condition evaluation with full project loading. 
- Use Microsoft.Build nuget package to have new csproj support 
- Use VS2017 in AppVeyor

### CODE REVIEW

**Comment by geoffreymcgill** [comment]
Hi @Danielku15 – We have a backlog of pr's waiting for final acceptance into the `v17` branch, then once those are complete we will be reviewing this pr in detail and hope to include in Bridge 17.0 as well. 

Thanks for this awesome revision.

**Comment by fabriciomurta** [comment]
Several changes were necessary to merge to Bridge 17 as per the recent commit list above.

**Comment by fabriciomurta** [comment]
In order to be able to merge this, the integration tests folder will have to be once again moved over to a different folder.

**Comment by fabriciomurta** [comment]
We can't push back changes to this pull request's branch, so we just created #3591 with the merged changes to the latest Bridge state.

**Pull request closed without merging**
