### PR TITLE
List ConvertAll added.

### PR DESCRIPTION
**Pull request by michaelcheers**
#997

### CODE REVIEW

**Comment by DaniilVeriga** [comment]
Hello @michaelcheers,

Thank you very much for the pull request

Before accepting we would need the CLA [form](http://goo.gl/forms/CvDFLA3EPO) accepted. You can find more information in [CONTRIBUTING.md](https://github.com/bridgedotnet/Bridge/blob/master/.github/CONTRIBUTING.md). 

The full CLA is available [here](http://bridge.net/cla/).

When you get a chance, please review the CLA and complete the [CLA Acceptance Form](http://goo.gl/forms/CvDFLA3EPO). If you have any questions, please just let me know.

**Comment by michaelcheers** [comment]
By the way, [The Bridge Cla](http://bridge.net/cla/) returns 404.[CLA 404 Redirect](https://github.com/bridgedotnet/Bridge/blob/master/CLA.md)
image

I've completed Google Forms by the way.

**Comment by DaniilVeriga** [comment]
Thank you for the report about the broken link. Corrected.

Thank you for signing CLA. The pull request is going to reviewed and probably merged into the next release.

**Comment by LeonidVeriga** [comment]
Hi @michaelcheers,

Thank you for the Pull Request. `ConvertAll` is very useful. We will include it into `1.11.1` release.

Please note the changes we made:
  - `ConvertAll` to match .Net signature `public extern List<TOutput> ConvertAll<TOutput>(Converter<T,  TOutput> converter)`
  - added a unit test.

**Pull request merged**
