### PR TITLE
[to v16] First steps to proper JSON.Parse and JSON.Stringify in the world of C#.

### LINKED ISSUE #98: JSON.Parse<T> does not work with object instances
Once implemented it is good to review this KB article:
http://bridge.net/kb/work-with-data

```c#
Foo foo = JSON.Parse<Foo>((string)obj)
```

### See Also

* http://forums.bridge.net/forum/community/help/130
* http://forums.bridge.net/forum/community/help/179
* http://forums.bridge.net/forum/general/feature-requests/1107
* http://forums.bridge.net/forum/bridge-net-pro/bugs/1417 (sub-objects)
* #894 (duplicate)
* #2302

### PR DESCRIPTION
**Pull request by TriEdgeAI**
Fixes #98 and #1306.
Could also help with #1192 and #1432 once some other issues are fixed, which are mentioned in comments in the code.

### CODE REVIEW

**Comment by LeonidVeriga** [comment]
Hi @TriEdgeAI,

Thank you for the implementation of JSON parsing that is very useful thing.

We are planning to include your feature into next Bridge 16.0.
A new branch [v16](https://github.com/bridgedotnet/Bridge/tree/v16) created for 16.0 release.

Can you please create a new Pull Request to be merged into branch **v16**.

**Comment by TriEdgeAI** [comment]
Awesome! Thanks! I'll have time to do it in a few days.

**Comment by LeonidVeriga** [comment]
#2043 has been fixed

**Comment by LeonidVeriga** [comment]
Hi @TriEdgeAI, the following issues has been fixed for **15.7** release and merged into **v16** branch:

#2050
#2051
#2052
#2056

**Comment by TriEdgeAI** [comment]
Awesome! I'll see how I can improve the JSON methods based on that :)

**Comment by TriEdgeAI** [comment]
I'll remake this pull request, because I've messed up my fork by committing with multiple emails.

**Pull request closed without merging**
