### PR TITLE
[2851] New console config for bridge.json and tests

### LINKED ISSUE #2851: New console config for bridge.json
A **bridge.json** `console` config to modify the functionality of the **Bridge Console**.

Name | Type | Description
---- | ---- | ----
enabled | bool | Set to `true` to include **Bridge Console**. Default is `false`.

#### Example

```js
{
  "console": {
    "enabled": true
  }
}
```

## See Also

* #1994
* https://forums.bridge.net/forum/bridge-net-pro/bugs/4434-combinescripts-and-resources-bridge-console-js-extract-false-doesn-t-exclude
* https://forums.bridge.net/forum/general/feature-requests/2781-open-1994-option-to-disable-bridge-console-does-this-already-exist

### PR DESCRIPTION
**Pull request by LeonidVeriga**
Fixes #2851 
```json
{
  "console": {
    "disabled": true
  }
}
```
Alternative syntax:
```json
{
  "console": false
}
```

### CODE REVIEW

**Comment by ProductiveRage** [comment]
This is great news! :)

**Comment by LeonidVeriga** [comment]
@ProductiveRage, sorry for buzzing, it would be super great if you have a chance to review https://forums.bridge.net/forum/bridge-net-pro/bugs/4434-combinescripts-and-resources-bridge-console-js-extract-false-doesn-t-exclude?p=4450#post4450

**Comment by ProductiveRage** [comment]
There's a lot here! Will read properly tomorrow :)

**Comment by ProductiveRage** [comment]
The new console changes look great. Having read through that forum thread, I will make a change to the ProductiveRage.Immutable.Extensions library to ensure that it's not packaging JS files that it's not directly responsible for.

**Comment by LeonidVeriga** [comment]
@ProductiveRage, I would consider it as a bug partially:
 - it is correct that it includes minified versions
- it is NOT correct that it includes core (**bridge.js** etc) and resources from referenced dlls (**Bridge.React.js** etc)

This config
```json
{
  "outputBy":  "Project",
  "fileName": "productiveRage.immutable.extensions.js"
}
```
should include the following resources:
- productiveRage.immutable.extensions.js
- productiveRage.immutable.extensions.min.js
- productiveRage.immutable.extensions.meta.js
- productiveRage.immutable.extensions.meta.min.js

So you would have to use `"outputFormatting": "Formatted",` to exclude **min** resources (if you don't need them), and the resources being included:
- productiveRage.immutable.extensions.js
- productiveRage.immutable.extensions.meta.js

**Comment by LeonidVeriga** [comment]
@ProductiveRage, the issue with embedding outputs from referenced dlls addressed in PR #2906.
> Having read through that forum thread, I will make a change to the ProductiveRage.Immutable.Extensions library to ensure that it's not packaging JS files that it's not directly responsible for.
Additionally, there is a new config option **report**  - if enabled it outputs a file listing resources being embedded into assembly (see  #2906.)

**Comment by ProductiveRage** [comment]
@LeonidVeriga I was thinking more about how these files are packaged into the DLLs - if the ProductiveRage.Immutable binary includes all of these:

productiveRage.immutable.extensions.js
productiveRage.immutable.extensions.min.js
productiveRage.immutable.extensions.meta.js
productiveRage.immutable.extensions.meta.min.js

And if I have a project that uses this NuGet package and specifies combineScripts: true, how does the build process know that it must only include one of "productiveRage.immutable.extensions.js" and "productiveRage.immutable.extensions.min.js"?

**Comment by LeonidVeriga** [comment]
Given a project has `combineScripts: true` and its output has:
* project.js

Given the project references Bridge.dll with:
* bridge.js
* bridge.meta.js

Given the project references a dll containing:
* resource1.js
* resource1.min.js
* resource2.js
* resource3.min.js

The project **formatted** output **projectName.js** will include:
* bridge.js
* bridge.meta.js
* resource1.js
* resource2.js
* resource3.min.js (as is)
* project.js

The project **minified** output **projectName.min.js** will include:
* bridge.js (minified by Bridge)
* bridge.meta.js (minified by Bridge)
* resource1.min.js (as is)
* resource2.js (minified by Bridge)
* resource3.min.js (as is)
* project.js (minified by Bridge)

I.e.:
* **resource1.js** and **resource1.min.js** are considered as one resource item. Bridge uses an appropriate version depending on formatting option;
* **resource2.js** goes into formatted output, if minified version required then Bridge mifies it;
* **resource3.min.js** goes into both formatted and minified outputs as is.

**Comment by ProductiveRage** [comment]
@LeonidVeriga Thanks for that, it all sounds good.

One final question.. :) Are **resource1.js** and **resource1.min.js** "considered as one resource item" based solely upon their file names or is there some additional metadata in the DLL that contains them?

**Comment by LeonidVeriga** [comment]
@ProductiveRage, no extra metadata, just resolving file names (additional settings may appear in **resources** config in future).

**Comment by LeonidVeriga** [comment]
@ProductiveRage, just FYI, there are some changes coming for the new **Report** option - see PR #2920.
We find this option usefull to monitor which resources being included into your project assembly - if the report file (by default, **bridge.report.log** in project's output folder) is under source control then it is very easy to see the changes (it would show changes in consist and size).

**Pull request merged**
