### PR TITLE
Gamepad support #781

### PR DESCRIPTION
**Pull request by michaelcheers**
Gamepad support.

### CODE REVIEW

**Comment by LeonidVeriga** [comment]
Addresses #781

**Comment by LeonidVeriga** [comment]
@michaelcheers, thank you for contridution. We will review your PR and try to include into 1.14.

**Comment by LeonidVeriga** [comment]
We just corrected some mispellings and merged PR into master. Thank you, @michaelcheers.

We appretiate you add XML comments into the code.

**Comment by michaelcheers** [comment]
@LeonidVeriga, it should be 
```csharp
[Namespace(false)]
```
 not 
```csharp
[Name(false)]
```
on Navigator.

**Comment by LeonidVeriga** [comment]
Yes, makes sense, the others as well. Thanks.

**Pull request merged**
