### PR TITLE
Issue490

### PR DESCRIPTION
**Pull request by fabriciomurta**
***IMPORTANT*** REBASED BRANCH: REMOVE YOUR LOCAL COPY OF THE `issue490` BRANCH BEFORE PULLING!!! DO NOT MERGE IT TO YOUR LOCAL COPY!

Fixes emitted code having whitespaces at end of line.

Fixes also one whitespace at end of line from bridge.js generated file.

Expect this to fix building from recent code cleanup already committed on master branch.

### CODE REVIEW

**Comment by LeonidVeriga** [comment]
@fabriciomurta, I merged latest changes into branch issue490. Please see my commit 44d6a1e
It reflect changes in how we generates output for jsdoc. Please see the diffs for files `testProject1.js` - there is no space between param name and description (and param type and description):
     * @param   {number}    iNumber of somethng
     * @return  {string}A good string

**Comment by fabriciomurta** [comment]
I see, thanks, I will fix this!

**Comment by fabriciomurta** [comment]
Related issue #490

**Comment by LeonidVeriga** [comment]
Merged changes into release1.10 126d1fd

**Pull request closed without merging**
