### PR TITLE
[1329] Enhanced support for yield

### PR DESCRIPTION
**Pull request by TriEdgeAI**
Addresses #1329

### CODE REVIEW

**Comment by vladsch** [comment]
Hi

I reviewed changes, it looks good but it doesn't work out of the box

- when you update interface members reference (like `this.getEnumerator = action;`) then you have to update alias also
```
this.getEnumerator = action;
this.System$Collections$IEnumerable$getEnumerator = action;
```

and 

```
this.moveNext = action;
this.System$Collections$IEnumerator$moveNext = action;
```

- `Bridge.GeneratorEnumerable` action function should returns `$enumerator` variable

I used the following test sample
```
public class App
    {
        public static void Main()
        {
            // Display powers of 2 up to the exponent of 8:
            foreach (int i in Power(2, 8))
            {
                Console.Write("{0} ", i);
            }
        }

        public static System.Collections.Generic.IEnumerable<int> Power(int number, int exponent)
        {
            int result = 1;

            for (int i = 0; i < exponent; i++)
            {
                result = result * number;
                Console.Write("return: " + result);
                yield return result;
            }
        }

        // Output: 2 4 8 16 32 64 128 256
    }
```

**Comment by TriEdgeAI** [comment]
Thank you! Will do some testing and make sure it works properly and update this PR.

**Comment by vladsch** [comment]
Thanks for your changes. Now test case works correctly
I found that yield doesn't work in properties

Test case
```
public class GalaxyClass
    {
        public static void Main()
        {
            var theGalaxies = new Galaxies();
            foreach (Galaxy theGalaxy in theGalaxies.NextGalaxy)
            {
                Console.WriteLine(theGalaxy.Name + " " + theGalaxy.MegaLightYears.ToString());
            }
        }

        public class Galaxies
        {

            public System.Collections.Generic.IEnumerable<Galaxy> NextGalaxy
            {
                get
                {
                    yield return new Galaxy { Name = "Tadpole", MegaLightYears = 400 };
                    yield return new Galaxy { Name = "Pinwheel", MegaLightYears = 25 };
                    yield return new Galaxy { Name = "Milky Way", MegaLightYears = 0 };
                    yield return new Galaxy { Name = "Andromeda", MegaLightYears = 3 };
                }
            }

        }

        public class Galaxy
        {
            public String Name { get; set; }
            public int MegaLightYears { get; set; }
        }
    }
```

Required changes:
```
 Compiler/Translator/Emitter/Blocks/AsyncBlock.cs | 25 +++++++++++++++++++++++-
 1 file changed, 24 insertions(+), 1 deletion(-)

diff --git a/Compiler/Translator/Emitter/Blocks/AsyncBlock.cs b/Compiler/Translator/Emitter/Blocks/AsyncBlock.cs
index bafa6543..7d333624 100644
--- a/Compiler/Translator/Emitter/Blocks/AsyncBlock.cs
+++ b/Compiler/Translator/Emitter/Blocks/AsyncBlock.cs
@@ -35,6 +35,18 @@ namespace Bridge.Translator
             this.AnonymousMethodExpression = anonymousMethodExpression;
         }
 
+        public AsyncBlock(IEmitter emitter, Accessor accessor)
+            : base(emitter, accessor)
+        {
+            this.Emitter = emitter;
+            this.Accessor = accessor;
+        }
+
+        public Accessor Accessor
+        {
+            get; set;
+        }
+
         public AstNode Node
         {
             get
@@ -54,6 +66,11 @@ namespace Bridge.Translator
                     return this.LambdaExpression;
                 }
 
+                if (this.Accessor != null)
+                {
+                    return this.Accessor;
+                }
+
                 return null;
             }
         }
@@ -101,6 +118,11 @@ namespace Bridge.Translator
                     return this.AnonymousMethodExpression.Body;
                 }
 
+                if (this.Accessor != null)
+                {
+                    return this.Accessor.Body;
+                }
+
                 return null;
             }
         }
@@ -208,7 +230,8 @@ namespace Bridge.Translator
 
         protected void DetectReturnType()
         {
-            AstNode node = this.MethodDeclaration != null ? this.MethodDeclaration.ReturnType : null;
+            var entityDeclaration = (EntityDeclaration)this.Accessor?.Parent;
+            AstNode node = this.MethodDeclaration?.ReturnType ?? entityDeclaration?.ReturnType;
 
             if (node == null)
             {

```

```
 .../Translator/Emitter/Blocks/GeneratorBlock.cs    | 33 ++++++++++++++++++----
 1 file changed, 28 insertions(+), 5 deletions(-)

diff --git a/Compiler/Translator/Emitter/Blocks/GeneratorBlock.cs b/Compiler/Translator/Emitter/Blocks/GeneratorBlock.cs
index caca2385..4000ecab 100644
--- a/Compiler/Translator/Emitter/Blocks/GeneratorBlock.cs
+++ b/Compiler/Translator/Emitter/Blocks/GeneratorBlock.cs
@@ -36,6 +36,18 @@ namespace Bridge.Translator
             this.AnonymousMethodExpression = anonymousMethodExpression;
         }
 
+        public GeneratorBlock(IEmitter emitter, Accessor accessor)
+            : base(emitter, accessor)
+        {
+            this.Emitter = emitter;
+            this.Accessor = accessor;
+        }
+
+        public Accessor Accessor
+        {
+            get; set;
+        }
+
         public AstNode Node
         {
             get
@@ -55,6 +67,11 @@ namespace Bridge.Translator
                     return this.LambdaExpression;
                 }
 
+                if (this.Accessor != null)
+                {
+                    return this.Accessor;
+                }
+
                 return null;
             }
         }
@@ -102,6 +119,11 @@ namespace Bridge.Translator
                     return this.AnonymousMethodExpression.Body;
                 }
 
+                if (this.Accessor != null)
+                {
+                    return this.Accessor.Body;
+                }
+
                 return null;
             }
         }
@@ -208,25 +230,26 @@ namespace Bridge.Translator
 
         protected void DetectReturnType()
         {
-            AstNode node = this.MethodDeclaration != null ? this.MethodDeclaration.ReturnType : null;
+            var entityDeclaration = (EntityDeclaration)this.Accessor?.Parent;
+            AstNode node = this.MethodDeclaration?.ReturnType ?? entityDeclaration?.ReturnType;
 
-            if(node == null)
+            if (node == null)
             {
                 node = this.AnonymousMethodExpression;
             }
 
-            if(node == null)
+            if (node == null)
             {
                 node = this.LambdaExpression;
             }
 
             var resolveResult = this.Emitter.Resolver.ResolveNode(node, this.Emitter);
 
-            if(resolveResult is LambdaResolveResult)
+            if (resolveResult is LambdaResolveResult)
             {
                 this.ReturnType = ((LambdaResolveResult)resolveResult).ReturnType;
             }
-            else if(resolveResult is TypeResolveResult)
+            else if (resolveResult is TypeResolveResult)
             {
                 this.ReturnType = ((TypeResolveResult)resolveResult).Type;
             }

```


```
 Compiler/Translator/Emitter/Blocks/VisitorIndexerBlock.cs | 13 ++++++++++++-
 1 file changed, 12 insertions(+), 1 deletion(-)

diff --git a/Compiler/Translator/Emitter/Blocks/VisitorIndexerBlock.cs b/Compiler/Translator/Emitter/Blocks/VisitorIndexerBlock.cs
index 98a1c488..49608ea8 100644
--- a/Compiler/Translator/Emitter/Blocks/VisitorIndexerBlock.cs
+++ b/Compiler/Translator/Emitter/Blocks/VisitorIndexerBlock.cs
@@ -90,7 +90,18 @@ namespace Bridge.Translator
 
                 if (script == null)
                 {
-                    accessor.Body.AcceptVisitor(this.Emitter);
+                    if (YieldBlock.HasYield(accessor.Body))
+                    {
+                        new GeneratorBlock(this.Emitter, accessor).Emit();
+                    }
+                    else if (accessor.HasModifier(Modifiers.Async))
+                    {
+                        new AsyncBlock(this.Emitter, accessor).Emit();
+                    }
+                    else
+                    {
+                        accessor.Body.AcceptVisitor(this.Emitter);
+                    }
                 }
                 else
                 {
```


```
 Compiler/Translator/Emitter/Blocks/VisitorPropertyBlock.cs | 13 ++++++++++++-
 1 file changed, 12 insertions(+), 1 deletion(-)

diff --git a/Compiler/Translator/Emitter/Blocks/VisitorPropertyBlock.cs b/Compiler/Translator/Emitter/Blocks/VisitorPropertyBlock.cs
index fd663660..28a170e0 100644
--- a/Compiler/Translator/Emitter/Blocks/VisitorPropertyBlock.cs
+++ b/Compiler/Translator/Emitter/Blocks/VisitorPropertyBlock.cs
@@ -96,7 +96,18 @@ namespace Bridge.Translator
 
                 if (script == null)
                 {
-                    accessor.Body.AcceptVisitor(this.Emitter);
+                    if (YieldBlock.HasYield(accessor.Body))
+                    {
+                        new GeneratorBlock(this.Emitter, accessor).Emit();
+                    }
+                    else if (accessor.HasModifier(Modifiers.Async))
+                    {
+                        new AsyncBlock(this.Emitter, accessor).Emit();
+                    }
+                    else
+                    {
+                        accessor.Body.AcceptVisitor(this.Emitter);
+                    }
                 }
                 else
                 {

```

**Comment by TriEdgeAI** [comment]
I added some of the proposed changes and skipped some of them. C# does not allow async getters/setter so I left those changes out. I also added support for generators that return IEnumerator, instead of IEnumerable.

**Comment by LeonidVeriga** [comment]
Hi @TriEdgeAI,

We incorporated your changes in this PR #2323, just added some changes.

**Pull request closed without merging**
