### PR TITLE
Fixes BYTES_PER_ELEMENT constants for typed arrays.

### LINKED ISSUE #1373: Literal Multiplied by BYTES_PER_ELEMENT wrong result
When you multiply a literal by Float32Array.BYTES_PER_ELEMENT, only literal value is returned.
Also tried casting to int.
### Expected

8
### Actual

2
### Steps To Reproduce

``` csharp
public class App
{
    public static void Main()
    {
        int numb0 = Float32Array.BYTES_PER_ELEMENT;
        //echo -> 4
        int numb1 = 2 * Float32Array.BYTES_PER_ELEMENT;
        //echo -> 2
    }
}
```

### PR DESCRIPTION
**Pull request by kvee33**
Fixes #1373.

Changes proposed in this pull request:

- Modify the actual `BYTES_PER_ELEMENT` constants

### CODE REVIEW

**Comment by fabriciomurta** [comment]
Hello @kvee33 ! Thanks for your contribution!

Just a little heads up, you should be looking into the `dev` branch, as code may already be changed or even the issue might already be fixed in that branch, that evolves as `master` sits stable.

**Comment by kvee33** [comment]
Hello,
no problem!
Thanks for telling me about the branches, well this is actually my first PR, so I was bound to overlook something :)

**Comment by fabriciomurta** [comment]
there's another issue with your pull req... as you didn't branch off and sent the pr from `master`, this will break some havoc.

Would you mind starting over (the right way) so we don't mess up your `master` mirror of Bridge?

Here's a rough step-thru:
- checkout your fork's `dev` branch
- sync it up with Bridge's
- branch _off_ `dev`, say to `Issue1373` (we usually use branch names after the issue numbers for easier tracking and conflict avoiding).
- apply the changes (the correct value to the constants)
- voila, create pull request again!

This way, as soon as we merge your changes to `dev` and you sync again, you'll get the changes you offered back to dev without conflicts and so on.

What you say, deal? I really feel like closing this pr unmerged and saving you the trouble to reset branches, etc. Potentially, following pull requests from your "tainted" master will be a lot of mishaps and overwrites...

But if you don't mind we tainting your `master` (as we have to merge to `dev` and also set up unit tests), just let us know. Once the pull request is merged, you will be able to hard-reset your `master` to whatever Bridge has.

So, your choice!

**Comment by kvee33** [comment]
I don't mind, I forked the repo only for this bugfix anyway.

**Comment by fabriciomurta** [comment]
Okay, waiting your new pull request from the fresh branch! It would be nice the fresh (and dev-based) pull request + branch. :)

**Pull request closed without merging**
