### PR TITLE
[3549] [3577]

### LINKED ISSUE #3549: "preventModuleName" argument value is not respected in non-external modules
If `[Module]` attribute is specified with a constructor argument `preventModuleName` set to `true`, the name of the module should not be emitted as a prefix in references to the module entities.

The issue is reproducible for non-external modules only. External modules process `preventModuleName` argument value correctly.

### Steps To Reproduce

https://deck.net/68bd3d55fd2684327594fd082313d8b0

```csharp
public class Program
{
    public static void Main()
    {
        var a = new test1.A();
        var b = new test2.B();
    }
}

[Bridge.Module(ModuleType.UMD, false, Name = "test1")]
public static class test1
{
    [Name("A")]
    public class A : Retyped.IObject
    {
    }
}

[Bridge.Module(ModuleType.UMD, true, Name = "test2")]
public static class test2
{
    [Name("B")]
    public class B : Retyped.IObject
    {
    }
}
```

### Expected Result

```js
// ... 
main: function Main () {
    var a = new test1.A();
    var b = new B();
}
// ...
```

### Actual Result

```js
// ... 
main: function Main () {
    var a = new test1.A();
    var b = new test2.B();  // Error:  "test2." is emitted regardless "preventModuleName" value
}
// ...
```

### PR DESCRIPTION
**Pull request by vladsch**
[3549] "preventModuleName" argument value is not respected in non-external modules
[3577] Module name escaping

Fixes #3549 and #3577

### CODE REVIEW

**Comment by fabriciomurta** [comment]
Just synced up to `dev`. Shouldn't have broken anything, hopefully (builds and runs fine)

**Comment by vladsch** [comment]
@AndreyChechel Please review additional commit with the fix

**Comment by AndreyChechel** [comment]
Works correctly now, thanks!

**Comment by fabriciomurta** [comment]
The exception output was not really helpful. Added the original exception's message to the output so errors during bridge.json file reading are properly handled.

The change by this issue implies that any new `Bridge.Contract.Module` instance should receive a reference to the translator's emitter. It seems the emitter is not available at the time or context that ReadConfig() lies within, or at least some parameter should be passed to the json deserialization command in order to effectively pass the emitter's reference to the constructor when type is `Bridge.Contract.Module`.

**Pull request merged**
