### PR TITLE
Source map support

### PR DESCRIPTION
**Pull request by LeonidVeriga**

### CODE REVIEW

**Comment by michaelcheers** [comment]
@LeonidVeriga, this is absolutely amazing but one question when will this be available. Since, bridge beta 2 was released 10 days ago and this was merged 29 days ago but I can't seem to get it to work except on dev.deck.net.

**Comment by LeonidVeriga** [comment]
@michaelcheers, this is available since **16.0.0-beta2**. There is a short description in #259 to turn on teh SourceMap feature in **bridge.json**: `"sourceMap": true`. Is that the case?

**Comment by geoffreymcgill** [comment]
Looks like `sourceMap` config documentation is missing from the [Global Configuration (bridge.json)](https://github.com/bridgedotnet/Bridge/wiki/global-configuration) wiki. I will add it right away.

**Comment by geoffreymcgill** [comment]
@michaelcheers – Source Map support is enabled on https://deck.net too. Not just the **dev** instance. The **Result** panel should be open in a separate browser tab. You might have to refresh that browser tab too to get the browser developer tools to instantiate the source map instance.

screenshot 2017-06-17 14 30 14

Hope this helps.

**Comment by michaelcheers** [comment]
@geoffreymcgill, thank you, this helps a lot.

**Comment by michaelcheers** [comment]
I still can't get it to work, I've enabled source maps in the Bridge.json file. Attached, is my Bridge project. Can you see if you can get it to generate source maps. I have checked I have 16.0.0-beta2.

Here is [my project](https://github.com/bridgedotnet/Bridge/files/1082962/IOTest.zip).

**Comment by LeonidVeriga** [comment]
@michaelcheers , at a first glance, you use 16.0.0-beta (not 16.0.0-beta2).

**Comment by michaelcheers** [comment]
@LeonidVeriga, I forget to do -pre on Update-Package.

**Pull request merged**
