### PR TITLE
Fixed #156 and general array behavior problems. See #1369.

### LINKED ISSUE #156: 1D array does not throw exception when referenced outside its boundaries
For C#, when an array is touched outside its allocated area, and exception is thrown, as it could be touching any unexpected memory address.

For JavaScript, this is not true. Accessing an array beyond its boundaries just returns 'null' if that's actually beyond arrays' defined data. Also returns null when the element has not been set (non-contiguous arrays).

```c#
namespace ClassLibrary1
{
    public partial class Class1
    {
        public static int[] MyArray = new int[5];
        public static int[,] My2DArray = new int[5, 5];

        public static void TriggerError()
        {
            Console.WriteLine("Array value outside its bounds is: " + MyArray[10]);
            Console.WriteLine("Next command will trigger an exception, whereas it should just show 'null'.");
            Console.WriteLine("Breaking array outside its bounds is: " + My2DArray[2, 10]);
        }
    }
}
```

Will result in the JS code:

```js
Bridge.define('ClassLibrary1.Class1', {
    statics: {
        config: {
            init: function () {
                this.myArray = new Array(5);
                this.my2DArray = Bridge.Array.create(0, null, 5, 5);
                Bridge.ready(this.triggerError);
            }
        },
        triggerError: function () {
            console.log("Array value outside its bounds is: " + ClassLibrary1.Class1.myArray[10]);
            console.log("Next command will trigger an exception, whereas it should just show 'null'.");
            console.log("Breaking array outside its bounds is: " + ClassLibrary1.Class1.my2DArray.get([2, 10]));
        }
    }
});
```

And an exception will be triggered once the third command on `triggerError` function is executed on the browser. The exception is thrown from Bridge.Array.get(), corresponding to:

```
Bridge.js:4275                     if (indices[i] < 0 || indices[i] >= arr.$s[i]) {
Bridge.js:4276                        throw new Bridge.ArgumentException("Index " + i + " out of range");
BRidge.js:4277                    }
```

A similar exception should be thrown for the myArray invalid access on the code above.

## See Also

* #2466

### PR DESCRIPTION
**Pull request by michaelcheers**
[In the last comment of #1369](https://github.com/bridgedotnet/Bridge/pull/1369/#issuecomment-222292597), I mentioned this.
It broke some of the arrays so I made this pull request which shouldn't do so badly for #156.

### CODE REVIEW

**Comment by LeonidVeriga** [comment]
Great, thanks @michaelcheers, we will review the pull request.

**Comment by LeonidVeriga** [comment]
@michaelcheers,

That is a good idea to use `System.Array.getItem` (please note the current Bridge code uses `System.Array` instead of `Bridge.Array`) in `EmitSingleDimArrayIndexer` method (but a trade-off is checking index vs performance). However, there are two problems with the fix:
-  it misses closing parentthesis as it added `this.Write("System.Array.getItem(");` but did not added extra `this.WriteCloseParentheses()`;
-  `arr[0] = "x";` -> ` System.Array.getItem(arr,  0) = "x";` causing error JS `Invalid left-hand side in assignment`

**Comment by michaelcheers** [comment]
@LeonidVeriga, I think you should make an option to use javascript indexer (s) instead of C# ones.

**Comment by michaelcheers** [comment]
@LeonidVeriga, [I did add a close parentheses](https://github.com/bridgedotnet/Bridge/pull/1407/files#diff-f417604a9c2ff661009df53a4e986d9fL1122). I'll change it to System.Array and setItem (for setItem only if I can figure out how to).

**Comment by LeonidVeriga** [comment]
@michaelcheers, regarding closing parentheses, yes, there is a call added ` this.WriteCloseParentheses();` but it is in a conditional `if` however the opening one ` this.Write("Bridge.Array.getItem(");` added unconditionally.

**Comment by LeonidVeriga** [comment]
Thanks @michaelcheers. We will review the changes and preliminary it looks good.
1.14 release scope is defined already; we will have an internal discussion on 1.14 release date early next week. If we have time we include this pull request into 1.14.

**Comment by michaelcheers** [comment]
@LeonidVeriga, I couldn't figure how to fix the setter problem.

**Comment by kcudnik** [comment]
It would be nice when config is set to  "overflowMode": "Javascript", then array behaviour should be as in javascritp, and not like in c#, this will have better performance for javascript code since no getItem() that checks index range will be required

**Comment by michaelcheers** [comment]
[Me too](https://github.com/bridgedotnet/Bridge/pull/1407#issuecomment-222538017)

**Comment by LeonidVeriga** [comment]
The change is going to be postponed.

**Pull request closed without merging**
